"""empty message

Revision ID: 020b85c177a2
Revises: 
Create Date: 2020-01-19 18:23:31.744958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020b85c177a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userName', sa.String(), nullable=True),
    sa.Column('isTeacher', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
