"""empty message

Revision ID: 1c976d494b5c
Revises: 
Create Date: 2020-01-18 22:54:11.512162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c976d494b5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('apiKey', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('userName', sa.String(), nullable=True),
    sa.Column('isTeacher', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
